### ISSUE TITLE
Please consider release the new commits

### ISSUE THREAD

**Issue by KaneGreen** [shadowsocks/crypto2#9]
On [crates.io], the lastest version is at commit 502efd0adab778c5a311ba22a72ec7915ae7235e.
The three new commits b4605b81c389d65b9cf9c2d850e4fe79b04601e8 773d32d4822ff0e13c8cd86c6ad44b1afa0c6cc8 618cda7c41640611fc3d3888268a7cd5bdee9eb8 are not released to [crates.io].

Please consider bump a new release and publish it to [crates.io]. Thank you.

[crates.io]: https://crates.io/crates/crypto2

**Comment by LuoZijun** [comment]
@KaneGreen 

`v0.1.2` has been released. See https://crates.io/crates/crypto2/versions .
